apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  apiServerPort: 30001
  apiServerAddress:
  podSubnet: "192.168.0.0/16"
  serviceSubnet: "192.168.0.0/16"
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            cgroup-root: "/kubelet"
            node-labels: "ingress-ready=true"
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            cgroup-root: "/kubelet"
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 30080
        hostPort: 80
        listenAddress: "0.0.0.0"
        protocol: TCP
      - containerPort: 30443
        hostPort: 443
        listenAddress: "0.0.0.0"
        protocol: TCP
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
          cgroup-root: "/kubelet"
          node-labels: "ingress-ready=true"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
          cgroup-root: "/kubelet"
          node-labels: "ingress-ready=true"
kubeadmConfigPatchesJSON6902:
